# Generated by Django 4.2.7 on 2023-11-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreamer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("paragraph_number", models.SmallIntegerField()),
            ],
        ),
    ]
