# Generated by Django 4.2.7 on 2023-11-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("newsfeed", "0001_initial"),
        ("dreamer", "0002_articleaudio"),
    ]

    operations = [
        migrations.AddField(
            model_name="articleaudio",
            name="article",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="newsfeed.article",
            ),
            preserve_default=False,
        ),
    ]
