# Generated by Django 4.2.7 on 2023-11-26 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("newsfeed", "0002_article_audio_generated_on_and_more"),
        ("dreamer", "0004_articlevideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[
                            ("Q", "Queued"),
                            ("I", "In Progress"),
                            ("C", "Complete Success"),
                            ("E", "Complete Error"),
                        ],
                        default="Q",
                        max_length=1,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("IGF", "Image Gen Full"),
                            ("IGP", "Image Gen Partial"),
                            ("AGF", "Audio Gen Full"),
                            ("AGP", "Audio Gen Partial"),
                            ("VG", "Video Gen"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status_message",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 11, 26, 15, 23, 27, 499295
                        )
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 11, 26, 15, 23, 27, 499295
                        )
                    ),
                ),
                ("job_args", models.TextField(blank=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsfeed.article",
                    ),
                ),
            ],
        ),
    ]
