# Generated by Django 4.2.7 on 2023-11-27 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreamer", "0005_dreamjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dreamjob",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 26, 21, 12, 35, 614845)
            ),
        ),
        migrations.AlterField(
            model_name="dreamjob",
            name="updated_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 26, 21, 12, 35, 614845)
            ),
        ),
    ]
