# Generated by Django 4.2.7 on 2023-11-28 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreamer", "0006_alter_dreamjob_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dreamjob",
            name="created_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 27, 20, 45, 28, 966745)
            ),
        ),
        migrations.AlterField(
            model_name="dreamjob",
            name="job_status",
            field=models.CharField(
                choices=[
                    ("Q", "Queued"),
                    ("I", "In Progress"),
                    ("C", "Complete Success"),
                    ("E", "Complete Error"),
                    ("O", "Complete Overriden"),
                ],
                default="Q",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="dreamjob",
            name="updated_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 27, 20, 45, 28, 966745)
            ),
        ),
    ]
