# Generated by Django 4.2.7 on 2023-11-27 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsfeed", "0002_article_audio_generated_on_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="audio_generated_on",
        ),
        migrations.RemoveField(
            model_name="article",
            name="images_generated_on",
        ),
        migrations.RemoveField(
            model_name="article",
            name="video_generated_on",
        ),
    ]
